### ISSUE TITLE
how do you use it without gx?

### ISSUE THREAD

**Issue by jvsteiner** [paralin/go-libp2p-kcp#2]
Given that all the libp2p libraries are using it, and one has to pass objects across library boundaries when using this, how do you solve issues like:

```
./narc.go:312:38: cannot use kcp.KcpTransport literal (type *kcp.KcpTransport) as type "gx/ipfs/QmbbNoAoAymAqijje51yTMbskK1vAQivR25s1BwuLuRksf/go-libp2p-transport".Transport in argument to swrm.AddTransport:
	*kcp.KcpTransport does not implement "gx/ipfs/QmbbNoAoAymAqijje51yTMbskK1vAQivR25s1BwuLuRksf/go-libp2p-transport".Transport (wrong type for Dialer method)
		have Dialer("github.com/multiformats/go-multiaddr".Multiaddr, ..."github.com/libp2p/go-libp2p-transport".DialOpt) ("github.com/libp2p/go-libp2p-transport".Dialer, error)
		want Dialer("gx/ipfs/QmWWQ2Txc2c6tqjsBpzg5Ar652cHPGNsQQp2SejkNmkUMb/go-multiaddr".Multiaddr, ..."gx/ipfs/QmbbNoAoAymAqijje51yTMbskK1vAQivR25s1BwuLuRksf/go-libp2p-transport".DialOpt) ("gx/ipfs/QmbbNoAoAymAqijje51yTMbskK1vAQivR25s1BwuLuRksf/go-libp2p-transport".Dialer, error)
FAIL
```

**Comment by paralin** [comment]
Basically run `gx-go uw` to un-rewrite the imports. Then I use dep or something else to control the libp2p package versions. Pinning everything to the current master is a safe place to start as any, considering how alpha all of this is. I haven't run into any issues though.

We are operating in production this way at the moment.

**Comment by jvsteiner** [comment]
out of curiosity, why not gx-ify this library, or use gx in production?

**Comment by paralin** [comment]
Working with GX at the moment is a bit of a pain, and I'm not convinced these particular versions will stay pinned forever, although I know that is a priority of the IPFS team.

When I last looked at gx, it looks really fast and cool, but seemed to over-complicate some things to solve problems that aren't particularly pressing at the moment (version pinning in Go and ditching GitHub entirely). I respect the goal completely and want to move to it eventually, though.

This library on the other hand - I would be happy to gx-ify to match the other IPFS libraries.

**Comment by jvsteiner** [comment]
fair
